name: Link Checker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linkChecker:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2.1.0
        id: lychee
        with:
          args: ". --no-progress --verbose"
          fail: true
          jobSummary: true
